# Generated by Django 4.2.11 on 2026-03-26 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='datasets/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('production_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('matching_type', models.CharField(choices=[('baseline', 'Baseline Matching'), ('enkf', 'Ensemble Kalman Filter (EnKF)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initial_pressure', models.FloatField(help_text='bar')),
                ('porosity', models.FloatField(help_text='%')),
                ('permeability', models.FloatField(help_text='mD')),
                ('water_saturation', models.FloatField(help_text='%')),
                ('progress', models.IntegerField(default=0, help_text='0-100 percentage')),
                ('total_steps', models.IntegerField(default=100)),
                ('current_step', models.IntegerField(default=0)),
                ('match_quality', models.FloatField(blank=True, help_text='0-100 matching percentage', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('results_data', models.JSONField(blank=True, default=dict, help_text='Simulation output and results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Execution duration in seconds', null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='simulations.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_simulations', models.IntegerField(default=0)),
                ('completed_simulations', models.IntegerField(default=0)),
                ('failed_simulations', models.IntegerField(default=0)),
                ('baseline_simulations', models.IntegerField(default=0)),
                ('enkf_simulations', models.IntegerField(default=0)),
                ('total_datasets_uploaded', models.IntegerField(default=0)),
                ('total_forecasts_generated', models.IntegerField(default=0)),
                ('avg_match_quality', models.FloatField(default=0.0)),
                ('avg_simulation_duration', models.IntegerField(default=0, help_text='in seconds')),
                ('best_match_quality', models.FloatField(default=0.0)),
                ('last_simulation_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Simulation Statistics',
                'db_table': 'simulation_statistics',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('forecast_type', models.CharField(choices=[('prior', 'Prior Forecast'), ('posterior', 'Posterior Forecast')], max_length=50)),
                ('forecast_date', models.DateField()),
                ('forecast_period_days', models.IntegerField(default=365, help_text='Forecast period in days')),
                ('predicted_parameters', models.JSONField(default=dict, help_text='Updated reservoir parameters')),
                ('predictions', models.JSONField(default=dict, help_text='Predicted production data')),
                ('uncertainty_bounds', models.JSONField(default=dict, help_text='Upper and lower uncertainty bounds')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='simulations.simulationrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forecast',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['user', '-created_at'], name='simulation__user_id_-created-_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['status'], name='simulation__status_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['user', '-generated_at'], name='forecast_user_id_-generated-_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['simulation'], name='forecast_simulation_id_idx'),
        ),
    ]
