# Generated by Django 6.0.3 on 2026-03-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="forecast",
            new_name="forecast_user_id_cb710d_idx",
            old_name="forecast_user_id_-generated-_idx",
        ),
        migrations.RenameIndex(
            model_name="forecast",
            new_name="forecast_simulat_69b5fc_idx",
            old_name="forecast_simulation_id_idx",
        ),
        migrations.RenameIndex(
            model_name="simulationrun",
            new_name="simulation__user_id_881e43_idx",
            old_name="simulation__user_id_-created-_idx",
        ),
        migrations.RenameIndex(
            model_name="simulationrun",
            new_name="simulation__status_8ebe70_idx",
            old_name="simulation__status_idx",
        ),
    ]
